const MovieActionTypes = {
  NOMINATE_MOVIE: "NOMINATE_MOVIE",
  WITHDRAW_NOMINATION: "WITHDRAW_NOMINATION",
  SEARCH_MOVIES_REQUEST: "SEARCH_MOVIES_REQUEST",
  SEARCH_MOVIES_SUCCESS: "SEARCH_MOVIES_SUCCESS",
  SEARCH_MOVIES_FAILURE: "SEARCH_MOVIES_FAILURE",
  SET_ALERT: "SET_ALERT",
  REMOVE_ALERT: "REMOVE_ALERT",
};

export default MovieActionTypes;
